### ISSUE TITLE
Push button to push a value to the google sheet.

### ISSUE THREAD

**Issue by arshadnas** [StorageB/Google-Sheets-Logging#1]
Hi, I tried to replace the random number generator with a push button to push a value to the google sheet. After burning the code to the NordMCU, everything works fine as I push the button, a value is logged into the Google Sheet. But when I leave the button/ESP8266 idle for a while(more than a minute) and later press the push button, it fails to push the value to the GS. I get '_Error! Not connected to host. Error while connecting_' in the serial monitor. But when I press the button again, it pushes the payload successfully. Is there any way to rectify this?

**Comment by StorageB** [comment]
I have run into this issue as well.  Occasionally it will fail the first time, but will work the second time if I try again immediately after. As far as I can tell, the problem is on the Google Sheets side of things. For applications where I am not publishing data on a regular interval but rather on an event trigger (such as only publishing data when a button is pressed), the code must be modified to attempt to publish again if it fails the first time.

I created a new example under the "Advanced" folder with modified code to send data on a button press instead of a regular time interval. The code will attempt to send again (up to 3 times) if it fails the first time.

https://github.com/StorageB/Google-Sheets-Logging/tree/master/Advanced

**Comment by arshadnas** [comment]
@StorageB  Thanks a lot for your update. Cheers!
