### ISSUE TITLE
Hey I had this issue when I run the ESP8266.cpp file after importing the HTTPSRedirect lib

### ISSUE THREAD

**Issue by ansel2000** [StorageB/Google-Sheets-Logging#2]
Hey I had this issue

'class HTTPSRedirect' has no member named 'setInsecure'

any idea what I'm doing wrong? Its pretty much the same code but with my credentials

**Comment by StorageB** [comment]
Hello @ansel2000 
I am not able to reproduce this error. 

"setInsecure" is a function of the WiFi library used. 

Are you using the same ESP8266WiFi library for the wifi connection that is used in the example code?

> Its pretty much the same code but with my credentials

I recommend starting from scratch following the instructions exactly and only changing the required information in order to get the script running initially before making any other changes or adding it to the code for your project.
